/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DeliveryInfo {
  'fullName' : string,
  'address' : string,
  'phoneNumber' : string,
}
export interface Order {
  'id' : bigint,
  'razorpayPaymentId' : [] | [string],
  'paymentStatus' : string,
  'fulfillmentStatus' : string,
  'createdAt' : bigint,
  'deliveryInfo' : DeliveryInfo,
  'razorpayOrderId' : string,
  'totalAmount' : bigint,
  'customerId' : Principal,
  'guestDeliveryInfo' : [] | [DeliveryInfo],
  'items' : Array<OrderItem>,
}
export interface OrderInput {
  'razorpayPaymentId' : string,
  'deliveryInfo' : DeliveryInfo,
  'razorpayOrderId' : string,
  'totalAmount' : bigint,
  'guestDeliveryInfo' : DeliveryInfo,
  'items' : Array<OrderItem>,
}
export interface OrderItem {
  'productId' : bigint,
  'quantity' : bigint,
  'unitPrice' : bigint,
}
export interface Product {
  'id' : bigint,
  'status' : ProductStatus,
  'specifications' : Array<Specification>,
  'stockQuantity' : bigint,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'isFeatured' : boolean,
  'category' : string,
  'priceInr' : bigint,
}
export interface ProductInput {
  'status' : ProductStatus,
  'specifications' : Array<Specification>,
  'stockQuantity' : bigint,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'isFeatured' : boolean,
  'category' : string,
  'priceInr' : bigint,
}
export type ProductStatus = { 'featured' : null } |
  { 'launchingSoon' : null } |
  { 'outOfStock' : null } |
  { 'notVisible' : null } |
  { 'visible' : null };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface SiteSettings {
  'razorpayKeyId' : string,
  'whatsappNumber' : string,
  'storeName' : string,
  'contactEmail' : string,
  'announcementBanner' : string,
}
export interface Specification { 'key' : string, 'value' : string }
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserSummary {
  'principal' : Principal,
  'orderCount' : bigint,
  'registeredAt' : bigint,
  'profile' : [] | [UserProfile],
}
export interface WhatsAppButtonSettings {
  'ringEffect' : boolean,
  'icon' : string,
  'animation' : string,
  'tooltip' : string,
  'pulseRingColor' : string,
  'enabled' : boolean,
  'buttonColor' : string,
  'number' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'confirmPayment' : ActorMethod<[bigint, string], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createOrder' : ActorMethod<[OrderInput], Order>,
  'createProduct' : ActorMethod<[ProductInput], Product>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllUsers' : ActorMethod<[], Array<UserSummary>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFeaturedProducts' : ActorMethod<[], Array<Product>>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getOrderById' : ActorMethod<[bigint], [] | [Order]>,
  'getOrders' : ActorMethod<[], Array<Order>>,
  'getPaginatedProducts' : ActorMethod<[bigint, bigint], Array<Product>>,
  'getProductById' : ActorMethod<[bigint], [] | [Product]>,
  'getProducts' : ActorMethod<[Array<ProductStatus>], Array<Product>>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'getRazorpayKeyId' : ActorMethod<[], string>,
  'getSiteSettings' : ActorMethod<[], SiteSettings>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWhatsappButtonSettings' : ActorMethod<[], WhatsAppButtonSettings>,
  'getWhatsappNumber' : ActorMethod<[], string>,
  'isAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isProductInStock' : ActorMethod<[bigint], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchProducts' : ActorMethod<[string], Array<Product>>,
  'setAdmin' : ActorMethod<[Principal], undefined>,
  'setSiteSettings' : ActorMethod<[SiteSettings], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'setWhatsappNumber' : ActorMethod<[string], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateFulfillmentStatus' : ActorMethod<[bigint, string], undefined>,
  'updateProduct' : ActorMethod<[bigint, ProductInput], Product>,
  'updateStock' : ActorMethod<[bigint, bigint], undefined>,
  'updateWhatsappButtonSettings' : ActorMethod<
    [WhatsAppButtonSettings],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];