/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const GuestDetails = IDL.Record({
  'city' : IDL.Text,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'state' : IDL.Text,
  'addressLine1' : IDL.Text,
  'addressLine2' : IDL.Text,
  'pincode' : IDL.Text,
  'phoneNumber' : IDL.Text,
  'orderNotes' : IDL.Opt(IDL.Text),
});
export const OrderItem = IDL.Record({
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Nat,
});
export const ShippingDetails = IDL.Record({
  'city' : IDL.Text,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'state' : IDL.Text,
  'addressLine1' : IDL.Text,
  'addressLine2' : IDL.Text,
  'pincode' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const OrderInput = IDL.Record({
  'razorpayPaymentId' : IDL.Text,
  'guestDetails' : GuestDetails,
  'razorpayOrderId' : IDL.Text,
  'totalAmount' : IDL.Nat,
  'items' : IDL.Vec(OrderItem),
  'shippingDetails' : ShippingDetails,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'razorpayPaymentId' : IDL.Opt(IDL.Text),
  'paymentStatus' : IDL.Text,
  'fulfillmentStatus' : IDL.Text,
  'createdAt' : IDL.Int,
  'guestDetails' : IDL.Opt(GuestDetails),
  'razorpayOrderId' : IDL.Text,
  'totalAmount' : IDL.Nat,
  'customerId' : IDL.Principal,
  'items' : IDL.Vec(OrderItem),
  'shippingDetails' : ShippingDetails,
});
export const ProductStatus = IDL.Variant({
  'featured' : IDL.Null,
  'launchingSoon' : IDL.Null,
  'outOfStock' : IDL.Null,
  'notVisible' : IDL.Null,
  'visible' : IDL.Null,
});
export const Specification = IDL.Record({
  'key' : IDL.Text,
  'value' : IDL.Text,
});
export const ProductInput = IDL.Record({
  'status' : ProductStatus,
  'specifications' : IDL.Vec(Specification),
  'stockQuantity' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'category' : IDL.Text,
  'priceInr' : IDL.Nat,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'status' : ProductStatus,
  'specifications' : IDL.Vec(Specification),
  'stockQuantity' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'category' : IDL.Text,
  'priceInr' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const UserSummary = IDL.Record({
  'principal' : IDL.Principal,
  'orderCount' : IDL.Nat,
  'registeredAt' : IDL.Int,
  'profile' : IDL.Opt(UserProfile),
});
export const SiteSettings = IDL.Record({
  'razorpayKeyId' : IDL.Text,
  'whatsappNumber' : IDL.Text,
  'storeName' : IDL.Text,
  'contactEmail' : IDL.Text,
  'announcementBanner' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const WhatsAppButtonSettings = IDL.Record({
  'ringEffect' : IDL.Bool,
  'icon' : IDL.Text,
  'animation' : IDL.Text,
  'tooltip' : IDL.Text,
  'pulseRingColor' : IDL.Text,
  'enabled' : IDL.Bool,
  'buttonColor' : IDL.Text,
  'number' : IDL.Text,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'confirmPayment' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createOrder' : IDL.Func([OrderInput], [Order], []),
  'createProduct' : IDL.Func([ProductInput], [Product], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserSummary)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getOrderById' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
  'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getPaginatedProducts' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getProductById' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getProducts' : IDL.Func(
      [IDL.Vec(ProductStatus)],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getProductsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getRazorpayKeyId' : IDL.Func([], [IDL.Text], ['query']),
  'getSiteSettings' : IDL.Func([], [SiteSettings], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWhatsappButtonSettings' : IDL.Func(
      [],
      [WhatsAppButtonSettings],
      ['query'],
    ),
  'getWhatsappNumber' : IDL.Func([], [IDL.Text], ['query']),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isProductInStock' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'setAdmin' : IDL.Func([IDL.Principal], [], []),
  'setSiteSettings' : IDL.Func([SiteSettings], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'setWhatsappNumber' : IDL.Func([IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateFulfillmentStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateProduct' : IDL.Func([IDL.Nat, ProductInput], [Product], []),
  'updateStock' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'updateWhatsappButtonSettings' : IDL.Func([WhatsAppButtonSettings], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const GuestDetails = IDL.Record({
    'city' : IDL.Text,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'state' : IDL.Text,
    'addressLine1' : IDL.Text,
    'addressLine2' : IDL.Text,
    'pincode' : IDL.Text,
    'phoneNumber' : IDL.Text,
    'orderNotes' : IDL.Opt(IDL.Text),
  });
  const OrderItem = IDL.Record({
    'productId' : IDL.Nat,
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Nat,
  });
  const ShippingDetails = IDL.Record({
    'city' : IDL.Text,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'state' : IDL.Text,
    'addressLine1' : IDL.Text,
    'addressLine2' : IDL.Text,
    'pincode' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const OrderInput = IDL.Record({
    'razorpayPaymentId' : IDL.Text,
    'guestDetails' : GuestDetails,
    'razorpayOrderId' : IDL.Text,
    'totalAmount' : IDL.Nat,
    'items' : IDL.Vec(OrderItem),
    'shippingDetails' : ShippingDetails,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'razorpayPaymentId' : IDL.Opt(IDL.Text),
    'paymentStatus' : IDL.Text,
    'fulfillmentStatus' : IDL.Text,
    'createdAt' : IDL.Int,
    'guestDetails' : IDL.Opt(GuestDetails),
    'razorpayOrderId' : IDL.Text,
    'totalAmount' : IDL.Nat,
    'customerId' : IDL.Principal,
    'items' : IDL.Vec(OrderItem),
    'shippingDetails' : ShippingDetails,
  });
  const ProductStatus = IDL.Variant({
    'featured' : IDL.Null,
    'launchingSoon' : IDL.Null,
    'outOfStock' : IDL.Null,
    'notVisible' : IDL.Null,
    'visible' : IDL.Null,
  });
  const Specification = IDL.Record({ 'key' : IDL.Text, 'value' : IDL.Text });
  const ProductInput = IDL.Record({
    'status' : ProductStatus,
    'specifications' : IDL.Vec(Specification),
    'stockQuantity' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'category' : IDL.Text,
    'priceInr' : IDL.Nat,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'status' : ProductStatus,
    'specifications' : IDL.Vec(Specification),
    'stockQuantity' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'category' : IDL.Text,
    'priceInr' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const UserSummary = IDL.Record({
    'principal' : IDL.Principal,
    'orderCount' : IDL.Nat,
    'registeredAt' : IDL.Int,
    'profile' : IDL.Opt(UserProfile),
  });
  const SiteSettings = IDL.Record({
    'razorpayKeyId' : IDL.Text,
    'whatsappNumber' : IDL.Text,
    'storeName' : IDL.Text,
    'contactEmail' : IDL.Text,
    'announcementBanner' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const WhatsAppButtonSettings = IDL.Record({
    'ringEffect' : IDL.Bool,
    'icon' : IDL.Text,
    'animation' : IDL.Text,
    'tooltip' : IDL.Text,
    'pulseRingColor' : IDL.Text,
    'enabled' : IDL.Bool,
    'buttonColor' : IDL.Text,
    'number' : IDL.Text,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'confirmPayment' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createOrder' : IDL.Func([OrderInput], [Order], []),
    'createProduct' : IDL.Func([ProductInput], [Product], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserSummary)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getOrderById' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
    'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getPaginatedProducts' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getProductById' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getProducts' : IDL.Func(
        [IDL.Vec(ProductStatus)],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getRazorpayKeyId' : IDL.Func([], [IDL.Text], ['query']),
    'getSiteSettings' : IDL.Func([], [SiteSettings], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWhatsappButtonSettings' : IDL.Func(
        [],
        [WhatsAppButtonSettings],
        ['query'],
      ),
    'getWhatsappNumber' : IDL.Func([], [IDL.Text], ['query']),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isProductInStock' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'setAdmin' : IDL.Func([IDL.Principal], [], []),
    'setSiteSettings' : IDL.Func([SiteSettings], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'setWhatsappNumber' : IDL.Func([IDL.Text], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateFulfillmentStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateProduct' : IDL.Func([IDL.Nat, ProductInput], [Product], []),
    'updateStock' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'updateWhatsappButtonSettings' : IDL.Func([WhatsAppButtonSettings], [], []),
  });
};

export const init = ({ IDL }) => { return []; };