/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Order {
  'id' : bigint,
  'razorpayPaymentId' : [] | [string],
  'paymentStatus' : string,
  'fulfillmentStatus' : string,
  'createdAt' : bigint,
  'razorpayOrderId' : string,
  'totalAmount' : bigint,
  'customerId' : Principal,
  'items' : Array<OrderItem>,
  'shippingDetails' : ShippingDetails,
}
export interface OrderInput {
  'razorpayOrderId' : string,
  'totalAmount' : bigint,
  'items' : Array<OrderItem>,
  'shippingDetails' : ShippingDetails,
}
export interface OrderItem {
  'productId' : bigint,
  'quantity' : bigint,
  'unitPrice' : bigint,
}
export interface Product {
  'id' : bigint,
  'status' : ProductStatus,
  'specifications' : Array<Specification>,
  'stockQuantity' : bigint,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'isFeatured' : boolean,
  'category' : string,
  'priceInr' : bigint,
}
export interface ProductInput {
  'status' : ProductStatus,
  'specifications' : Array<Specification>,
  'stockQuantity' : bigint,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'isFeatured' : boolean,
  'category' : string,
  'priceInr' : bigint,
}
export type ProductStatus = { 'active' : null } |
  { 'launchingSoon' : null } |
  { 'outOfStock' : null };
export interface ShippingDetails {
  'city' : string,
  'fullName' : string,
  'email' : string,
  'state' : string,
  'addressLine1' : string,
  'addressLine2' : string,
  'pincode' : string,
  'phoneNumber' : string,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface SiteSettings {
  'razorpayKeyId' : string,
  'whatsappNumber' : string,
  'storeName' : string,
  'contactEmail' : string,
  'announcementBanner' : string,
}
export interface Specification { 'key' : string, 'value' : string }
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserSummary {
  'principal' : Principal,
  'orderCount' : bigint,
  'registeredAt' : bigint,
  'profile' : [] | [UserProfile],
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Order owner or admin: confirm payment for an order.
   */
  'confirmPayment' : ActorMethod<[bigint, string], undefined>,
  /**
   * / Authenticated users only: create a Stripe checkout session.
   */
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  /**
   * / Authenticated users only: place a new order.
   */
  'createOrder' : ActorMethod<[OrderInput], Order>,
  /**
   * / Admin-only: create a new product.
   */
  'createProduct' : ActorMethod<[ProductInput], Product>,
  /**
   * / Admin-only: delete a product.
   */
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  /**
   * / Admin-only: get all products including hidden/draft ones.
   */
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  /**
   * / Admin-only: list all registered users with profile and order summary.
   */
  'getAllUsers' : ActorMethod<[], Array<UserSummary>>,
  /**
   * / Authenticated users only: get the caller's own profile.
   */
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Public: get featured products for the storefront.
   */
  'getFeaturedProducts' : ActorMethod<[], Array<Product>>,
  /**
   * / Authenticated users only: list the caller's own orders.
   */
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  /**
   * / Order owner or admin: get a single order by id.
   */
  'getOrderById' : ActorMethod<[bigint], [] | [Order]>,
  /**
   * / Admin-only: list all orders.
   */
  'getOrders' : ActorMethod<[], Array<Order>>,
  /**
   * / Public: paginated product listing.
   */
  'getPaginatedProducts' : ActorMethod<[bigint, bigint], Array<Product>>,
  /**
   * / Public: get a single product by id (storefront).
   */
  'getProductById' : ActorMethod<[bigint], [] | [Product]>,
  /**
   * / Public: browse all products (storefront).
   */
  'getProducts' : ActorMethod<[], Array<Product>>,
  /**
   * / Public: filter products by category.
   */
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  /**
   * / Public: returns only the Razorpay public key needed by the checkout page.
   * / The Razorpay Key ID is a client-side public key and must be readable by
   * / any visitor so that the checkout flow works without authentication.
   */
  'getRazorpayKeyId' : ActorMethod<[], string>,
  /**
   * / Admin-only: read the full site settings (includes sensitive config).
   */
  'getSiteSettings' : ActorMethod<[], SiteSettings>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  /**
   * / Owner or admin: get a specific user's profile.
   */
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWhatsappNumber' : ActorMethod<[], string>,
  'isAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / Public: check whether a product is in stock.
   */
  'isProductInStock' : ActorMethod<[bigint], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  /**
   * / Authenticated users only: save the caller's own profile.
   */
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  /**
   * / Public: full-text search over product name and description.
   */
  'searchProducts' : ActorMethod<[string], Array<Product>>,
  /**
   * / Bootstrap or admin-only: set the admin principal.
   * / When no admin has been set yet, any authenticated caller may claim admin.
   * / Once an admin is set, only the current admin can change it.
   */
  'setAdmin' : ActorMethod<[Principal], undefined>,
  /**
   * / Admin-only: persist updated site settings.
   */
  'setSiteSettings' : ActorMethod<[SiteSettings], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'setWhatsappNumber' : ActorMethod<[string], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  /**
   * / Admin-only: update the fulfillment status of an order.
   */
  'updateFulfillmentStatus' : ActorMethod<[bigint, string], undefined>,
  /**
   * / Admin-only: update an existing product.
   */
  'updateProduct' : ActorMethod<[bigint, ProductInput], Product>,
  /**
   * / Admin-only: update stock quantity for a product.
   */
  'updateStock' : ActorMethod<[bigint, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];